version: '3.7'

services:
  bb-app:
    image: terriadsit/fibonacci-web-app
    environment: 
      MONGO_URI_FILE: /run/secrets/mongo_uri
      COOKIE_KEY_1_FILE: /run/secrets/cookie_key_1
      COOKIE_KEY_2_FILE: /run/secrets/cookie_key_2
      CLIENT_ID_FILE: /run/secrets/client_id
      CLIENT_SECRET_FILE:  /run/secrets/client_secret
    ports:
      - "3000:8000"
    secrets:
      - mongo_uri
      - cookie_key_1
      - cookie_key_2
      - client_id
      - client_secret
  
secrets:
  mongo_uri:
    file: mongo_uri.txt
  client_id:
    external: true
    # file: client_id.txt
  client_secret:
    file: client_secret.txt
  cookie_key_1:
    file: cookie_key_1.txt
  cookie_key_2:
    file: cookie_key_2.txt