name: fibonacci web app CI
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs: 
  build: 
    env:
      CI: true
      MONGO_URL: mongodb://localhost/test
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      COOKIE_KEY_1: ${{ secrets.COOKIE_KEY_1 }}
      COOKIE_KEY_2: ${{ secrets.COOKIE_KEY_2 }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
    strategy: 
      matrix: 
        node-version: [14.x, 16.x, 18.x]
        mongodb-version: ['4.2', '4.4', '5.0', '6.0']
    runs-on: [ ubuntu-latest ]
    steps: 
      - uses: actions/checkout@v2

      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with: 
          node-version: ${{ matrix.node-version }}

      - name: Use MongoDB from GitHub actions
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - run: npm install --prefix client
      - run: npm install --prefix server
      - run: npm install 
      - run: npm run build --prefix client
      - run: npm run start --prefix server 
      - run: npm run test --prefix server
     